blank_issues_enabled: true
contact_links:
  - name: What's New
    url: https://pylint.pycqa.org/en/latest/whatsnew/
    about: What's new in the latest pylint releases
  - name: User manual
    url: http://pylint.pycqa.org/en/latest/
  - name: Technical references
    url: http://pylint.pycqa.org/en/latest/technical_reference/index.html
    about: Documentation to develop on pylint
  - name: Contributing
    url: http://pylint.pycqa.org/en/latest/development_guide/contribute.html
    about: Get started to contribute to pylint efficientely
  - name: Discord server
    url: https://discord.gg/Egy6P8AMB5
    about: Place to ask small questions and organize
