[tool.pylint]
enable = ["c-extension-no-member"]
disable = [
    "C0103",
    "C0114",
    "C0115",
    "C0116",
    "C0301",
    "C0413",
    "C0415",
    "E1101",
    "R0901",
    "R0902",
    "R0903",
    "R0904",
    "R0911",
    "R0913",
    "R0914",
    "W0212",
    "W0221",
]
ignore = "migrations"
max-line-length = 80
