import argparse


class ConfigFile:

    def __init__(self, config: argparse.Namespace):
        self.config = config

    def is_message_enabled(self, msgid_or_symbol: str) -> bool: ...

    def is_message_disabled(self, msgid_or_symbol: str) -> bool: ...

    def is_extension_loaded(self, extension: str) -> bool: ...

    def has_option(self, option: str) -> bool: ...

    def add_extension(self, extension: str) -> None: ...

    def remove_extension(self, extension: str) -> None: ...

    def enable_message(self, msgid_or_symbol: str) -> None: ...

    def disable_message(self, msgid_or_symbol: str) -> None: ...

    def remove_from_enable(self, msgid_or_symbol: str) -> None: ...

    def remove_from_disable(self, msgid_or_symbol: str) -> None: ...

    def remove_option(self, option: str) -> None: ...

    def rename_option(self, old_name: str, new_name: str) -> None: ...
